
-- 1. Tabella modelli (Catalogo)
CREATE TABLE modelli_prodotto (
    id_modello NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_modello VARCHAR2(50) NOT NULL UNIQUE, 
    nome VARCHAR2(100) NOT NULL,
    descrizione VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(100) NOT NULL,
    prezzo_listino NUMBER(10, 2) NOT NULL,
    CONSTRAINT chk_prezzo_modello CHECK (prezzo_listino >= 0)
);

-- 2. Tabella prodotti (Il Magazzino fisico)
CREATE TABLE prodotti (
    id_prodotto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_modello NUMBER NOT NULL,
    cod_seriale VARCHAR2(50) NOT NULL UNIQUE,
    data_arrivo DATE NOT NULL,
    disponibilita CHAR(1) DEFAULT 'S',
    CONSTRAINT fk_prod_modello FOREIGN KEY (id_modello) REFERENCES modelli_prodotto(id_modello),
    CONSTRAINT chk_disp CHECK (disponibilita IN ('S', 'N'))
);

-- 3. Tabella Clienti
CREATE TABLE clienti (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    cognome VARCHAR2(50) NOT NULL,
    data_nascita DATE NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE
);

-- 4. Testata Ordine
CREATE TABLE ordini (
    id_ordine NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER NOT NULL,
    data_ordine TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    prezzo_totale_pagato NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_ordini_clienti FOREIGN KEY (id_cliente) REFERENCES clienti(id_cliente)
);

-- 5. Tabella Dettagli Ordine
CREATE TABLE dettagli_ordine (
    id_dettaglio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ordine NUMBER NOT NULL,
    id_prodotto NUMBER NOT NULL UNIQUE,
    prezzo_vendita_effettivo NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_det_ordine FOREIGN KEY (id_ordine) REFERENCES ordini(id_ordine),
    CONSTRAINT fk_det_prodotto FOREIGN KEY (id_prodotto) REFERENCES prodotti(id_prodotto)
);

-- 6. Garanzie
CREATE TABLE garanzie (
    id_garanzia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prodotto NUMBER NOT NULL UNIQUE,
    data_inizio DATE NOT NULL,
    durata_mesi NUMBER DEFAULT 24 NOT NULL,
    stato_garanzia VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_gar_prod FOREIGN KEY (id_prodotto) REFERENCES prodotti(id_prodotto),
    CONSTRAINT chk_stati CHECK (stato_garanzia IN ('attiva', 'scaduta', 'in assistenza'))
);