-- 1. Pulizia tabelle esistenti (ordine inverso rispetto alle FK)
DROP TABLE verifiche_studenti CASCADE CONSTRAINTS;
DROP TABLE verifiche CASCADE CONSTRAINTS;
DROP TABLE materie CASCADE CONSTRAINTS;
DROP TABLE docenti CASCADE CONSTRAINTS;
DROP TABLE studenti CASCADE CONSTRAINTS;
DROP TABLE classi CASCADE CONSTRAINTS;

-- 2. Creazione tabelle di base
CREATE TABLE classi (
    id_classe    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR2(5) NOT NULL UNIQUE,  
    anno         NUMBER NOT NULL                 
);

CREATE TABLE studenti (
    id_studente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricola       VARCHAR2(10) NOT NULL UNIQUE,
    nome            VARCHAR2(50) NOT NULL,
    cognome         VARCHAR2(50) NOT NULL,
    data_nascita    DATE NOT NULL,
    id_classe       NUMBER NOT NULL,
    email           VARCHAR2(100),
    telefono        VARCHAR2(20),
    data_iscrizione DATE DEFAULT CURRENT_DATE,
    CONSTRAINT fk_studenti_classe FOREIGN KEY (id_classe) 
        REFERENCES classi(id_classe) ON DELETE CASCADE
);

CREATE TABLE docenti (
    id_docente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(50) NOT NULL,
    cognome    VARCHAR2(50) NOT NULL,
    email      VARCHAR2(100)
);

CREATE TABLE materie (
    id_materia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(50) NOT NULL,
    id_docente NUMBER,
    CONSTRAINT fk_materie_docente FOREIGN KEY (id_docente) 
        REFERENCES docenti(id_docente)
);

-- 3. Nuova Tabella: Sessioni di Verifica (L'evento "compito in classe")
CREATE TABLE verifiche (
    id_verifica   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_materia    NUMBER NOT NULL,
    id_classe     NUMBER NOT NULL, -- La classe intera che sostiene la prova
    data_verifica DATE NOT NULL,
    tipo          VARCHAR2(20),    -- Scritto, Orale, Pratico
    note          VARCHAR2(255),
    CONSTRAINT fk_sess_materia FOREIGN KEY (id_materia) REFERENCES materie(id_materia),
    CONSTRAINT fk_sess_classe FOREIGN KEY (id_classe) REFERENCES classi(id_classe) ON DELETE CASCADE
);

-- 4. Nuova Tabella: Voti Studenti (Il dettaglio per ogni partecipante)
CREATE TABLE verifiche_studenti (
    id_voto       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_verifica   NUMBER NOT NULL,
    id_studente   NUMBER NOT NULL,
    voto          NUMBER(3,1),
    commento      VARCHAR2(255),
    CONSTRAINT fk_voto_sessione FOREIGN KEY (id_verifica) REFERENCES verifiche(id_verifica) ON DELETE CASCADE,
    CONSTRAINT fk_voto_studente FOREIGN KEY (id_studente) REFERENCES studenti(id_studente) ON DELETE CASCADE
);